const fs = require('fs');
const path = require('path');
const Converter = require('../src/Converter');

describe('Converter Integration Test', () => {
    const inputEpub = path.resolve(__dirname, 'fixtures/test.epub');
    const outputDir = path.resolve(__dirname, '../output_test');
    const outputMd = path.join(outputDir, 'test.md');

    // Ensure test.epub exists (it should have been generated by previous steps)
    if (!fs.existsSync(inputEpub)) {
        throw new Error('test.epub not found. Please generate it first.');
    }

    // Clean up output before test
    if (fs.existsSync(outputDir)) {
        fs.rmSync(outputDir, { recursive: true, force: true });
    }

    test('should convert EPUB to Markdown with correct structure', async () => {
        const converter = new Converter();
        await converter.convert(inputEpub, outputDir);

        expect(fs.existsSync(outputMd)).toBe(true);

        const content = fs.readFileSync(outputMd, 'utf-8');

        // 1. Check Frontmatter
        expect(content).toContain('title: "Complex Test Book"');
        expect(content).toContain('tags: [epub, book]');

        // 2. Check ATX Headers
        // Note: Our anchor injection puts <a id="..."></a> INSIDE or BEFORE the content text depending on regex.
        // Current output: "# <a id=\"intro\"></a>Introduction"
        expect(content).toMatch(/#\s*<a id="intro"><\/a>Introduction/);
        expect(content).toMatch(/#\s*<a id="chap2"><\/a>Visuals & Links/);

        // 3. Check Anchor Injection (ID preservation)
        // Already verified above.

        // 4. Check Link Rewriting
        // Link to anchor in same file
        expect(content).toContain('(#local-anchor)');

        // Link to another chapter's section
        // Note: epub-gen merges contents, so "chapter2.xhtml#chap2-section" might become internal link if paths match.
        // In our generated epub, we used explicit filenames?
        // No, epub-gen handles it.
        // The output showed: `[local anchor](#local-anchor)`
        // And footnote: `[](#note1)`

        expect(content).toContain('(#chap2-section)');
        expect(content).toContain('(#note1)');

        // 5. Check Image Extraction
        const assetsDir = path.join(outputDir, 'assets');
        expect(fs.existsSync(assetsDir)).toBe(true);
        const files = fs.readdirSync(assetsDir);
        // Expect cover and one image
        expect(files.some(f => f.endsWith('.jpg') || f.endsWith('.jpeg'))).toBe(true);

        // Check image markdown
        // ![A random placeholder image](assets/...)
        expect(content).toMatch(/!\[A random placeholder image\]\(assets\/.*\.jpe?g\)/);

    }, 30000); // 30s timeout
});
